[project]
name = "autoglm-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.124.0",
    "openai>=2.9.0",
    "pillow>=11.3.0",
    "uvicorn>=0.38.0",
]
